name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd hello_test/
        make install
    - name: Lint with pylint
      run: |
        cd hello_test/
        make lint
    - name: Test with pytest
      run: |
        cd hello_test/
        make test
